name: Build and Release Extension

on:
  push:
    tags:
      - "vsc/v*"
  workflow_dispatch:

permissions:
  contents: write # This is needed to create releases

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/vsc-extension/openapi-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Copy assets
        run: cp -r ../../core/dist ./core-dist

      - name: Package Extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Publish to VS Code Marketplace
        if: success()
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "src/vsc-extension/openapi-ui/*.vsix"
          draft: false
          prerelease: false
          generate_release_notes: true
