name: Deploy Sample API to Azure

on:
  push:
    branches: [master]
    paths:
      - "src/c-sharp/JakubKozera.OpenApiUi.Sample/**"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: openapi-ui
  AZURE_WEBAPP_PACKAGE_PATH: "./src/c-sharp/JakubKozera.OpenApiUi.Sample"
  DOTNET_VERSION: "9.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/JakubKozera.OpenApiUi.Sample.csproj

      - name: Build application
        run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/JakubKozera.OpenApiUi.Sample.csproj --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/JakubKozera.OpenApiUi.Sample.csproj --configuration Release --no-build --output ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./publish
